# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20170718_1615'),
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
    ]
