# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-28 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_auto_20200328_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra',
            field=models.CharField(blank=True, help_text='Ex.: Bloco A, apto. 40, casa 2', max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Apenas números.', max_length=8, verbose_name='CEP'),
        ),
    ]
