# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20200328_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='extra',
            field=models.CharField(blank=True, help_text='Ex.: Bloco A, apto. 40, casa 2', max_length=50, null=True, verbose_name='Complemento'),
        ),
    ]
