# Generated by Django 2.2.13 on 2020-06-29 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_auto_20200329_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_address_related_created_by', related_query_name='address_addresss_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='modified_by',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_address_related_modified_by', related_query_name='address_addresss_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_address_related_owner', related_query_name='address_addresss_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
